#!/bin/bash

YEAR=$(date +%Y)
DAY=$(TZ=UTC date +%-d)

# Get input
./script/get-input.sh $YEAR $DAY

if [[ -f "lib/adventofcode/$YEAR/$DAY.rb" ]]; then
  echo "SOLUTION FILE FOR $YEAR DAY $DAY ALREADY EXISTS";
  exit 1;
fi

# Copy template in place
cp lib/adventofcode/template.rb lib/adventofcode/$YEAR/$DAY.rb
sed -i "" "s/DayN/Day$DAY/g" lib/adventofcode/$YEAR/$DAY.rb

# go!
open https://adventofcode.com/$YEAR/day/$DAY
vim lib/adventofcode/$YEAR/$DAY.rb spec/adventofcode_spec.rb
