#!/bin/bash

if [[ $1 == "" ]]; then
  YEAR=$(date +%Y)
  DAY=$(TZ=UTC date +%-d)
else
  YEAR=$1
  DAY=$2
fi

# Get input
./script/get-input.sh $YEAR $DAY

if [[ -f "lib/adventofcode/$YEAR/$DAY.rb" ]]; then
  echo "SOLUTION FILE FOR $YEAR DAY $DAY ALREADY EXISTS";
  exit 1;
fi

# Copy template in place
cp lib/adventofcode/template.rb lib/adventofcode/$YEAR/$DAY.rb
sed -i '' -e "s/DayN/Day$DAY/g" lib/adventofcode/$YEAR/$DAY.rb
sed -i '' -e "s/YearN/Year$YEAR/g" lib/adventofcode/$YEAR/$DAY.rb

# Copy spec in place
cp lib/adventofcode/spec_template.rb spec/adventofcode_${YEAR}_${DAY}_spec.rb
sed -i '' -e "s/YEAR/$YEAR/g" spec/adventofcode_${YEAR}_${DAY}_spec.rb
sed -i '' -e "s/DAY/$DAY/g" spec/adventofcode_${YEAR}_${DAY}_spec.rb

git status
